JPA and tests
java-park-mail-ru/Gwent-09-2017 pull request #3
Opened 2017-10-19 08:51 UTC by kgulyy

Иван, посмотрите пожалуйста

2017-10-19 09:27 UTC, isopov commented
Так... давайте коммиты, которые относятся к первому РК отсюда уберем...

2017-10-19 09:27 UTC, isopov requested changes
В комментариях будут замечания

2017-10-19 10:01 UTC, kgulyy commented
Как это сделать?

2017-10-19 10:39 UTC, isopov commented
1. SessionService, SessionDao - удаляем и пользуемся классом HttpSession. Просто в него кладем хоть бы и модель пользователя (это нормально и в реальных проектах так и делается на самом деле):
```
        session.setAttribute(SESSION_PROFILE_KEY, profile);
        UserProfile profile = session.getAttribute(SESSION_PROFILE_KEY);
```
2. DEFINED_PORT - это для очень дремучего legacy, и в нормальных проектах не надо делать такие тесты. Надо на RANDOM_PORT
3. Пароли в базе надо хранить с шифрованием - https://park.mail.ru/blog/topic/view/7197/

А так вообще всё хорошо.

2017-10-19 12:55 UTC, kgulyy commented
Готово

2017-10-20 12:22 UTC, kgulyy commented
Не сливайте пока PR, хотим дописать тесты и провести рефакторинг.

2017-10-23 11:31 UTC, kgulyy commented on src/test/java/ru/mail/park/gwent/controllers/SessionControllerTest.java
> +        verify(session).getAttribute(anyString());
на этой проверке падает, соответственно сессия замокана неверно

2017-10-23 12:53 UTC, kgulyy commented on src/test/java/ru/mail/park/gwent/controllers/SessionControllerTest.java
> +        final ResponseEntity<Message> response = restTemplate.getForEntity(AUTH_URL, Message.class);
Как сюда передать MockHttpSession?

2017-10-23 21:18 UTC, kgulyy commented
Иван, готово, можно проверять и мержить

2017-10-25 13:14 UTC, isopov approved these changes

2017-10-25 13:14 UTC, merged