WebSocket, Lobby & Mechanics
java-park-mail-ru/Gwent-09-2017 pull request #4
Opened 2017-11-29 18:57 UTC by kgulyy

РК №3
Выстроена транспортная система на веб-сокетах, сделано объединение пары игроков в Lobby.
Механика и тесты в процессе, но уже можно смотреть)

2017-11-30 07:55 UTC, KSolovyev commented
добавьте ссылку на фронт в описание пр

2017-11-30 08:00 UTC, KSolovyev commented
напишите парочку игровых тестов, аля игра началась, раздались карты. Карты в руку попали верные, один сходил, второй сходил - количество карт в руке уменьшилось и тд

2017-11-30 08:05 UTC, KSolovyev requested changes

2017-11-30 08:05 UTC, KSolovyev commented on src/main/java/ru/mail/park/gwent/websocket/handler/GameWebSocketHandler.java
> +            session.getAttributes().put(Constants.SESSION_WEB_SOCKET_USER_KEY, webSocketUser);
вы кладете в сессию изменяемый объект. Обычно это становится источником багов. Попробуйте класть что-нибудь неизменяемое

2017-11-30 08:05 UTC, KSolovyev commented on src/main/java/ru/mail/park/gwent/websocket/handler/GameWebSocketHandler.java
> +            session.getAttributes().put(Constants.SESSION_WEB_SOCKET_USER_KEY, webSocketUser);
а еще у вас здесь на одного пользователя может быть несколько websocket-сессий. Это нормально?

2017-11-30 08:24 UTC, kgulyy commented on src/main/java/ru/mail/park/gwent/websocket/handler/GameWebSocketHandler.java
> +            session.getAttributes().put(Constants.SESSION_WEB_SOCKET_USER_KEY, webSocketUser);
Это чтобы из под одной учетки можно было сразу на нескольких устройствах играть.

2017-11-30 08:30 UTC, kgulyy commented on src/main/java/ru/mail/park/gwent/websocket/handler/GameWebSocketHandler.java
> +            session.getAttributes().put(Constants.SESSION_WEB_SOCKET_USER_KEY, webSocketUser);
А по поводу изменяемого объекта не вижу проблемы, он либо есть в сессии и я его использую, либо создаю новый и сохраняю в сессию.

2017-12-01 06:00 UTC, kgulyy commented on src/main/java/ru/mail/park/gwent/websocket/handler/GameWebSocketHandler.java
> +            session.getAttributes().put(Constants.SESSION_WEB_SOCKET_USER_KEY, webSocketUser);
Обсудили при встрече на РК, исправлю)

2017-12-18 18:59 UTC, KSolovyev commented
Тестов нет(

2017-12-18 18:59 UTC, KSolovyev commented
ссылка на фронт изменилась. Поменяйте, пожалуйста

2017-12-21 08:39 UTC, kgulyy commented
Тесты добавил, к РК №3 все готово

2017-12-21 10:20 UTC, KSolovyev commented
А механики игровой пока нет, что ли?

2017-12-21 10:43 UTC, kgulyy commented
Есть, но не доработана еще до конца.

2017-12-21 13:47 UTC, KSolovyev requested changes

2017-12-21 13:47 UTC, KSolovyev commented on src/main/java/ru/mail/park/gwent/services/dao/UserDao.java
> +            final int position = offset + i;
вы же уже в запросе указали limit offset. Зачем еще раз это делать?

2017-12-21 13:47 UTC, KSolovyev commented on src/main/java/ru/mail/park/gwent/mechanics/Mechanics.java
> +        final CopyOnWriteArrayList<Card> cards = new CopyOnWriteArrayList<>();
а зачем здесь CopyOnWriteArrayList?

2017-12-21 13:54 UTC, kgulyy commented on src/main/java/ru/mail/park/gwent/services/dao/UserDao.java
> +            final int position = offset + i;
Позицию в таблице лидеров для каждого игрока вычисляю на момент запроса.

2017-12-21 14:49 UTC, kgulyy commented on src/main/java/ru/mail/park/gwent/mechanics/Mechanics.java
> +        final CopyOnWriteArrayList<Card> cards = new CopyOnWriteArrayList<>();
Это был костыль от ConcurrentModificationException.
Разобрался что дело было не в многопоточном доступе, а в не правильной раздачи карт из колод.
Исправил)

2017-12-21 16:24 UTC, KSolovyev commented on src/main/java/ru/mail/park/gwent/services/dao/UserDao.java
> +            final int position = offset + i;
ok

2017-12-22 15:33 UTC, Badya commented on src/main/java/ru/mail/park/gwent/mechanics/GameMechanicsImpl.java
> +    public void step(Player player, StepMessage message) {
не очень понятно зачем 2 таких похожих метода сделаны, вроде как логично было бы сделать общий, а линию и руку просто по игроку вычислять. Руку может быть даже внутри игрока хранить.

2017-12-22 15:38 UTC, kgulyy commented on src/main/java/ru/mail/park/gwent/mechanics/GameMechanicsImpl.java
> +    public void step(Player player, StepMessage message) {
Согласен, к сожалению, уже времени не остается поправить это.

2017-12-22 21:16 UTC, KSolovyev approved these changes

2017-12-22 21:16 UTC, merged